package eniso;


/**
* eniso/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* mardi 11 novembre 2025 13 h 50 GMT+01:00
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
