package eniso;


/**
* eniso/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* mardi 11 novembre 2025 13 h 50 GMT+01:00
*/

public interface CalcOperations 
{
  int div (int a, int b) throws eniso.DivByZeroException;
} // interface CalcOperations
