package eniso;

/**
* eniso/DivByZeroExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calc.idl
* mardi 11 novembre 2025 13 h 50 GMT+01:00
*/

public final class DivByZeroExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public eniso.DivByZeroException value = null;

  public DivByZeroExceptionHolder ()
  {
  }

  public DivByZeroExceptionHolder (eniso.DivByZeroException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = eniso.DivByZeroExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    eniso.DivByZeroExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return eniso.DivByZeroExceptionHelper.type ();
  }

}
